### ISSUE TITLE
Create templates for issues and PRs

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#25]
## Issue Overview

Currently there is no templates for new issues or new PRs

## Proposed Solutions or Ideas

Create this two templates, look at this [reference](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/main/.github)

**Comment by Supa-mega** [comment]
I’d like to resolve this.

**Comment by abdegenius** [comment]
Is this issue still available?

**Comment by JoelVR17** [comment]
### Request to Work on Creating Templates for Issues and Pull Requests  

Hello, team!  
I'm Joel Vargas | Dojo Coding  

I would like to take on the task of creating templates for new issues and pull requests as described in the issue. My plan is to ensure these templates provide clear and structured guidance for contributors, streamlining the process of submitting issues and PRs.  

#### Plan of Action:  
1. **Issue Template**:  
   - Design a comprehensive template for submitting new issues, including sections like description, steps to reproduce, expected behavior, and additional context.  

2. **Pull Request Template**:  
   - Create a template to standardize PR submissions, including sections for the purpose of the PR, changes made, related issues, and testing steps.  

3. **Reference and Adherence**:  
   - Use the provided reference to guide the structure and ensure alignment with the team's standards and workflows.  

#### Expected Outcome:  
- Two well-structured templates added to the repository: one for new issues and another for PRs.  
- Improved clarity and consistency in issue reporting and PR submissions.  

I will ensure that these templates are intuitive and align with the contributor’s guidelines. Please let me know if there are additional expectations or preferences for this task.  

Thank you!  
**Joel Vargas**

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success. 

I will create two templates: one for new issues and one for new pull requests (PRs). The issue template will include sections for providing a brief overview, the motivation for addressing the issue, and any required features. The PR template will outline proposed solutions or ideas for resolving the issue. Both templates will be designed to guide contributors in providing necessary details for effective collaboration.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
May I be assigned to this?

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Can I take this from here?

**Comment by Baronvil** [comment]
Could I try solving this?

**Comment by DuendexCR** [comment]
May I be assigned to this?

**Comment by josephpdf** [comment]
Hi @gianalarcon 
I'm Joseph Poveda, a member of the Dojo Coding community, I have experience in different programming languages ​​and have contributed to different OSS projects.
To solve the issue I propose
1. **Analyze the Reference**:
   - Review the issue and PR templates from the provided link for structure and content.
2. **Design Templates**:
   - Create an issue template that includes sections for a clear description, steps to reproduce, expected behavior, and actual behavior.
   - Develop a PR template with sections for the purpose, related issues, testing, and a checklist.
3. **Implement and Test**:
   - Add the templates to the `.github` folder in the repository.
   - Test for clarity and usability.
4. **Submit PR**:
   - Push the changes and submit a PR for review.

**Comment by GideonBature** [comment]
I’m interested in this one.

**Comment by gianalarcon** [comment]
All yours @zleypner.  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.
Note: This is an **NON-REWARDED**  issue. Please refer to the OD platform/team for more details.

**Comment by zleypner** [comment]
Yes, I am actually currently working on it. Thank you for assigning me!
